# Generated by Django 4.2.4 on 2023-08-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(max_length=50)),
                ('menu_name', models.CharField(max_length=20)),
                ('cooking_method', models.CharField(max_length=10)),
                ('cooking_standard', models.CharField(max_length=10)),
                ('main_ingredient_type', models.CharField(max_length=10)),
                ('cooking_kind', models.CharField(max_length=10)),
                ('ingredients', models.CharField(max_length=100)),
                ('cooking_volume', models.CharField(max_length=10)),
                ('cooking_level', models.CharField(max_length=5)),
                ('cooking_time', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
    ]
