# Generated by Django 4.2.3 on 2023-08-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_result_kind_result_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
