# Generated by Django 4.2.3 on 2023-08-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_getvideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetVideo',
        ),
    ]
