# Generated by Django 4.2.3 on 2023-08-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_delete_getvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
            options={
                'db_table': 'rating',
            },
        ),
    ]
