# Generated by Django 4.2.3 on 2023-08-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
