# Generated by Django 4.2.3 on 2023-08-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_remove_rating_rating_remove_rating_recipe_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='recipe_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
